### ISSUE TITLE
玩具种类管理问题

### ISSUE THREAD

**Issue by eric23** [hiyosoft/aoe#3]
现在是玩具匹配的属性，价格等都是绑定在玩具种类上的，如果用户通过孩子特性匹配到了一个玩具种类，那么：
1. 会出现多个品牌的玩具都符合要求，前台如何筛选
2. 各品牌价格会一样，这不合理

如果是产品包里，同样存在该问题。

**Comment by eric23** [comment]
个人感觉 玩具种类 比较冗余，在前台也体现不出来，建议将属性放到玩具上会比较合理，本身可以保留作为玩具分类方便统计和分类展示。不同品牌同一种类的玩具的产品描述也不会是一样的。

**Comment by dishi790529** [comment]
已经按照讨论的结果修改
